
<html>
<head>
<!--script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script--> 
<script src="/test/jquery-1.11.0.min.js" type="text/javascript"></script>
<style>
.acau
{
height:300px;
display: block;
overflow:auto;
}
</style>
<script>
function validatedate(inputText)  
{  
  var dateformat = /^\d{4}[-](0?[1-9]|1[012])[-](0?[1-9]|[12][0-9]|3[01])$/;   
  // Match the date format through regular expression 

if(inputText.match(dateformat))  
  {  
  var opera2 = inputText.split('-');  
  lopera2 = opera2.length;  
  // Extract the string into month, date and year  

if (lopera2>1)  
  {  
  var pdate = inputText.split('-');  
  }  

  var dd = parseInt(pdate[2]);  
  var mm  = parseInt(pdate[1]);  
  var yy = parseInt(pdate[0]);  

// Create list of days of a month [assume there is no leap year by default]  
  var ListofDays = [31,28,31,30,31,30,31,31,30,31,30,31];  
  if (mm==1 || mm>2)  
  {  
  if (dd>ListofDays[mm-1])  
  {  
  alert('Invalid date format!');  
  return false;  
  }  
  }  
  
if (mm==2)  
  {  
  var lyear = false;  
  
if ( (!(yy % 4) && yy % 100) || !(yy % 400))   
  {  
  lyear = true;  
  }  
 
if ((lyear==false) && (dd>=29))  
  {  
  alert('Invalid date format!');  
  return false;  
  }  
  
if ((lyear==true) && (dd>29))  
  {  
  alert('Invalid date format!');  
  return false;  
  }

  }
  
  }  

  else  
  {  
  alert("Invalid date format!");  
//  document.JoinDate.focus();  
  return false;  
  }  

  return true;
  }    

</script>

<script>
function pdetail(id)
{
var url="usrdtl?idn="+id, popn="usrdtl"
var w=1200,h=600;
var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;
width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var newWindow = window.open(url, popn, 'scrollbars=yes, location=no, resizable=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    // Puts focus on the newWindow
    if (window.focus) {     
        newWindow.focus();
    }	
	

}
</script>


<script>
function por(id)
{
//alert(id);
//w=window.open ("",'rcdpro','fullscreen=yes,toolbar=no,location=no,directories=no, width=700, height=400, status=no,menubar=no,scrollbars=no,resizable=no');
//nw.moveTo(150,240);
alert(id);
var cas=document.getElementById(id).value;
var url="rcdp?idn="+id+"&case="+cas,popn="rcdp";
var w=480,h=400;
    // Fixes dual-screen position                         Most browsers      Firefox
    var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
    var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

    width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
    height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

    var left = ((width / 2) - (w / 2)) + dualScreenLeft;
    var top = ((height / 2) - (h / 2)) + dualScreenTop;
    var newWindow = window.open(url, popn, 'scrollbars=no, location=no, resizable=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);

    // Puts focus on the newWindow
    if (window.focus) {     
        newWindow.focus();
    }
}
</script>



<script>
function validate()
{
//if (isNaN(document.getElementById("idn").value) || isNaN(document.getElementById("age").value))...ID will be generated by system automatically....
if (isNaN(document.getElementById("age").value))
{
alert ("Age should be a number");
return false;
}

if (document.getElementById("sex").value=="" || document.getElementById("JoinDate").value=="" || document.getElementById("fn").value=="" || document.getElementById("ln").value=="" || document.getElementById("idn").value=="" || document.getElementById("age").value=="")
{
alert ("Pls input all information");
return false;
}

inputText=document.getElementById("JoinDate").value;
if (!validatedate(inputText))
{return false;}

return true;
}
</script>


</head>

<body>

<form action="<?php pathinfo($_SERVER['PHP_SELF']);?>" method="POST" onsubmit="return validate()">
<a>ID: </a><input type="text" name="id" id="idn" disabled='true' value='Generated by system'></input>
<a>FirstName: </a><input type="text" name="fname" id="fn"></input>
<a>LastName: </a><input type="text" name="lstname" id="ln"></input>
<a>Age: </a><input type="text" name="age" id="age"></input>
<a>Sex: </a><select name="sex" id="sex"><option value=''></option><option value='Male'>Male</option><option value='Female'>Female</option></select>
<a>Join Date: </a><input type="text" name="JoinDate" id="JoinDate">(yyyy-mm-dd)</input>
<input type="submit" value="Add"></input>
<div id="info"></div>
</form>
<hr>

<div id="bdy" style="width:1400px;height:600px;">
<div id="usrlst" style="background-color:#ddffdd;width:1000px;height:530px;float:left;">
<div id="fdiv" style="display:inline;float:left;width:1000px;height:520px;position:absolute;">
<?php

//---------------for handling the "add" action triggerred by itself-----------------------
if ($_SERVER["REQUEST_METHOD"]=="POST")
{
 $con=mysqli_connect("localhost","ivan","440103","ivan");
 // Check connection
 if (mysqli_connect_errno()) 
   echo "Failed to connect to MySQL: " . mysqli_connect_error();
 
//$sql="alter TABLE Persons add column id int";

$firstn= $_POST["fname"];
$lstn=$_POST["lstname"];
$age=$_POST["age"];
// $id=$_POST["id"];  id will be generated by system basing on the available id number table idbase
$sex=$_POST["sex"];
$JoinDate=$_POST["JoinDate"];

$sql="select id from idbase limit 0, 1";
$rst=mysqli_query($con,$sql);
if(!$rst)
echo "Error selecting table: " . mysqli_error($con);

$rcd = mysqli_fetch_array($rst); 
$id=$rcd['id'];

$sql="delete from idbase where id='".$id."'";
$rst=mysqli_query($con,$sql);

//$sql="select * from persons where id='".$id."'";
//$rst=mysqli_query($con,$sql);
//if(!$rst)
//echo "Error selecting table: " . mysqli_error($con);

//if(mysqli_fetch_array($rst))
//echo "<script>alert('duplicate id');</script>";

//else
{
$sql="INSERT INTO PERSONS VALUES ('" . $firstn ."','" . $lstn."','" .$age. "','" . $id . "','" . $JoinDate . "','" . $sex . "')";

if (!mysqli_query($con,$sql)) 
echo "Error inserting table: " . mysqli_error($con);

$sql="select * from agestat where ageb<='".$age ."' and agee>='" . $age . "'";
if (!mysqli_query($con,$sql)) 
echo "Error selecting table: " . mysqli_error($con);
else
{$sql="update agestat set number=number+1 where ageb<='".$age ."' and agee>='" . $age . "'";
 if (!mysqli_query($con,$sql)) 
 echo "Error updating table: " . mysqli_error($con);}

}
mysqli_close($con);
echo "<script>alert('id: ".$id." is generated for the new record!');</script>";
}


//---------------for selecting number of records to be shown by page(on the left side cell)-----------------------
$max=14;
$cal=0;

echo "<table border='1' width='1000' height='520'><tr><td width='650' valign = 'top'>
<table border='1' width='620' height='510'>
<tr><td valign='top' height='480'>
<table border='1' width='610'>
 <tr>
 <th width='80'>ID</th>
 <th>Firstname</th>
 <th>Lastname</th>
 <th width='35'>Age</th>
 <th width='60'>Sex</th>
 <th width='100'>Join Date</th>
 <th>Action</th>
 </tr>";

if( isset($_GET["page"] ) )//check if "page" parameter is passed
       // page is passed, that means user at least finish one page browsing
{       
   $page = $_GET["page"] + 1;      //calculate the next page number
   $offset = $max * $page ;        //calculate the no. of first record to be shown in this new page
}
else   // No page is passed, that means user now is browsing the first page
{
$page=0;
$offset=0;
}

$con=mysqli_connect("localhost", "ivan","440103","ivan");
if(mysqli_connect_errno())
  echo "Failed to connect to MySQL: " . mysqli_connect_error();

$sql="select count(*) from persons";
$rst=mysqli_query($con,$sql);
if(!$rst)
echo "Error selecting table: " . mysqli_error($con);

$rcd = mysqli_fetch_array($rst, MYSQL_NUM);  
$total=$rcd[0];                  //get the total record number of a file
$remain=$total-($page*$max);     //calculate the number of record still not yet display at this moment(before showing the current new page)

$sql="select * from persons limit ".$offset.", ".$max;  //select designated number of record after the end of prior page
$rst=mysqli_query($con,$sql);
if(!$rst)
echo "Error selecting table: " . mysqli_error($con);

while($rcd=mysqli_fetch_array($rst))
{
$id=$rcd['id'];
echo "<tr>";
   echo "<td  align='center'><a href='#' onclick=pdetail(this.text)>" . $rcd['id'] . "</a></td>";
   echo "<td  align='center'>" . $rcd['FirstName'] . "</td>";
   echo "<td  align='center'>" . $rcd['LastName'] . "</td>";
   echo "<td  align='center'>" . $rcd['Age'] . "</td>";
   echo "<td  align='center'>" . $rcd['sex'] . "</td>";
   echo "<td  align='center'>" . $rcd['JoinDate'] . "</td>";
   echo "<td align='center'><select id='".$id."' onchange='por(this.id)'><option value=' '>None</option><option value='d'>Delete</option><option value='c'>Change</option></select></td>";
   echo "</tr>";
}
mysqli_close($con); //close the connection for the left cell database operation
echo "</td></table></td></tr><tr><td valign='bottom'><table border='1' width='610'><tr><td width='500' align='right'>";

if ($remain>$max)
//$ln="href=".$_SERVER["PHP_SELF"]."?page=".$page;  ***  $_SERVER["PHP_SELF"] will return the extension(.php), 
//if we don't want the extension of our webpage be shown the address line, we can use the below command to strip 
//the path conten only[but we need to enable the server(current one is Apache) rewrite model function and also and create a alian name for our page
$ln="href=".pathinfo($_SERVER['PHP_SELF'], PATHINFO_FILENAME)."?page=".$page;
else
$ln="";
echo "<a ".$ln.">Next</a>";
echo "</td><td align='center'>";

if ($page==0)
$ln="";
else 
{
$page=$page-2;
$ln="href=".$_SERVER["PHP_SELF"]."?page=".$page;
}

echo "<a ".$ln.">Previous</a>";

echo "</td></tr></table></td></tr></table></td>";

//------------------------preparing the age statistic on the right cell-------------------------

echo "<td valign='top'>
<table border='1' width='350'>
 <tr>
 <th align='left' width='60'>Range</th>
 <th align='left'>Count</th>
 <th width='280' align='left'>Statistic</th>
 </tr>";

$con=mysqli_connect("localhost", "ivan","440103","ivan");
if(mysqli_connect_errno())
  echo "Failed to connect to MySQL: " . mysqli_connect_error();
$sql="select * from agestat";
$rst=mysqli_query($con,$sql);
if(!$rst)
echo "Error selecting table: " . mysqli_error($con);

while($rcd=mysqli_fetch_array($rst))
{
if ($total!=0)
$lnth=280*($rcd['number']/$total);
else
$lnth=0;

echo "<tr>";
  echo "<td>" . $rcd['ageb'] . "-".$rcd['agee']. "</td>";
  echo "<td align='center'>" . $rcd['number'] . "</td>";
  echo "<td><img src='poll.gif' width='" . $lnth . "' height='20'></td>";
  echo "</tr>";

}
mysqli_close($con);

echo "</table></td></tr></table>";


?>
</div>
<div id="fltdiv" style="display:inline;width:1000px;height:530px;position:absolute;display:none;">

</div>
</div>
<div id="srch" style="background-color:#09a280;width:300px;height:530px;float:left;">

<fieldset class="acau">
<legend>Searching condition</legend>
<select id="srch_lst">
  <option value="id">ID</option>
  <option value="FirstName">Firstname</option>
  <option value="LastName">Lastname</option>
  <option value="sex">Sex</option>
  <option value="Age">Age</option>
  <option value="JoinDate">Join Date</option>
</select>
<input id="fltkey_value" type="text"></input><button>more...</button><button onclick=srch(-2)>search</button><button onclick=flsts()>back to full list</button>

<script>
$fld="";
$val="";
$nxtpage=0;
$prepage=0;
function srch($cpage)
{
$("#fltdiv").html(" ");
$table=	"<table border='1' width='1000' height='520'><tr><td width='650' valign = 'top'>";
$table += "<table border='1' width='620' height='510'>";
$table += "<tr><td valign='top' height='480'>";
$table += "<table id='fltt' border='1' width='610'>";
$table += "<tr>";
$table += "<th width='80'>ID</th>";
$table += "<th>Firstname</th>";
$table += "<th>Lastname</th>";
$table += "<th width='35'>Age</th>";
$table += "<th width='60'>Sex</th>";
$table += "<th width='100'>Join Date</th>";
$table += "<th>Action</th>";
$table += "</tr>";	
//$("#fltdiv").html($table);		
//alert($("#fltdiv").html());

//prepare and format searched table content
if($cpage == -2)// mark down the criteria only when search button is pressed(going to show the first page), if this function is triggered 
//by next/pre function, then no need to get the criteria again
{
$fld=$("#srch_lst").val();
$val=$("#fltkey_value").val();
}

reauest=$.ajax({
                        type: 'POST',
                        url: 'srchusr.php',
                        data: { "key_field":$fld, "key_value":$val,"page":$cpage },
                        dataType: 'json',
                        success: function(data){ 
					//	alert(JSON.stringify(data)); 
						$tbcnt=" ";  //need to initialize before += operation
						$.each(data, function(i,val){
                        $sid=val.id;
                        $sfname=val.FirstName;
						$slname=val.LastName;
                        $ssex=val.sex;
						$sage=val.Age;	
                        $sjdate=val.JoinDate;	 

//alert($nxtpage+"$$"+$prepage);
if (val.nxtpage==undefined || val.prepage==undefined) // to ignore treating the page control object as the record information
{
$tbcnt+= "<tr>";
$tbcnt+= "<td  align='center'><a href='#' onclick=pdetail(this.text)>" + $sid + "</a></td>";
$tbcnt+= "<td  align='center'>" + $sfname + "</td>";
$tbcnt+= "<td  align='center'>" + $slname + "</td>";
$tbcnt+= "<td  align='center'>" + $sage + "</td>";
$tbcnt+= "<td  align='center'>" + $ssex + "</td>";
$tbcnt+= "<td  align='center'>" + $sjdate + "</td>";
$tbcnt+= "<td align='center'><select id='"+$sid+"' onchange='por(this.id)'><option value=' '>None</option><option value='d'>Delete</option><option value='c'>Change</option></select></td>";
$tbcnt+= "</tr>";	
}
else
{
$nxtpage=val.nxtpage;  // page control information
$prepage=val.prepage;  // page control information
}
//$("#fltdiv").html($("#fltdiv").html()+$tbcnt);				
						});
						
$tbcnt+="</table></td></tr><tr><td valign='bottom'><table border='1' width='610'><tr><td width='500' align='right'>";
if ($nxtpage==-2)
$tbcnt+="<a disabled='true'>Next</a>";
else
$tbcnt+="<a href='#' onclick=pgchg("+$nxtpage+")>Next</a>";

$tbcnt+="</td><td align='center'>";

if($prepage==-2)
$tbcnt+="<a disabled='true'>Previous</a>";
else
$tbcnt+="<a href='#' onclick=pgchg("+$prepage+")>Previous</a>";

$tbcnt+="</td></tr></table></td></tr></table></td>";
$tbcnt+="</table>";
$fcnt=$table+$tbcnt;   //assemble the full table output in one go
$("#fltdiv").html($fcnt);	
//alert($("#fltdiv").html());
						}
				});	

if($cpage==-2 )// do the hide and show action only when the search button is pressed
//if this function is triggered by next/pre, no need to do this
{
$("#fdiv").hide("slow");
$("#fltdiv").show("slow");		
}

}

function flsts()
{
$("#fltdiv").hide("slow");
$("#fdiv").show("slow");
}

function pgchg($cpage)
{
srch($cpage);
}
</script>
<!--button onclick=$('#fdiv').hide('slow');>click</button>
<button onclick=$('#fdiv').show('slow');>click</button>
<button onclick=$('#fltdiv').show('slow');>show</button-->

</fieldset>


</div>

</div>

</body>
</html>
